### ISSUE TITLE
Create modules for GitLab and Github

### ISSUE THREAD

**Issue by boczkowska** [boczkowska/test#12]
- [ ] Create two concept modules which would briefly introduce the reader to GitLab and Github (what they are, why `git` and `Github` is not the same thing etc)
- [ ] Create an assembly file `git-hosting-services`, include GitLab and Github modules in it, **include this assembly file in the main master assembly**

**Comment by ossontoes** [comment]
Resolved in https://github.com/boczkowska/test/pull/20.
