### ISSUE TITLE
add attributes for github and gitlab

### ISSUE THREAD

**Issue by boczkowska** [boczkowska/test#17]
- [ ] create attributes for github and gitlab titles, replace instances of github and gtlab with attributes (*don't* do it manually, use `grep` and `sed`: https://stackoverflow.com/questions/15402770/how-to-grep-and-replace)
- [ ] create an attribute for github and gitlab web addresses, within this attribute use attribute of the repsective titles aka `:github-link: {github-title}.com`

**Comment by ossontoes** [comment]
Resolved in https://github.com/boczkowska/test/pull/27.
