### ISSUE TITLE
create docs/ directory

### ISSUE THREAD

**Issue by boczkowska** [boczkowska/test#19]
Create `docs/` directory, move all of the documentation with the exception of README.md into it. Move index.html into it also.

Research a smart instead of a manual solution if you feel curious: https://stackoverflow.com/questions/670460/move-all-files-except-one

**Comment by boczkowska** [comment]
Make sure to update image includes since the path to the images would change.

**Comment by boczkowska** [comment]
@ossontoes if you can, try to finish these last two issues by Friday. We will have our Git Cheat Sheet website up on GitHub pages and will leave this repo as a playground fro testing new things. :) But you're going to be moving to the real docs work soon.

**Comment by ossontoes** [comment]
Sure, I'll finish all of them by Friday.

**Comment by boczkowska** [comment]
I have renamed master.html to index.html because GitHub Pages is stupid and doesn't understand it otherwise. :D Make sure to pull the changes.

Other than that... TA-DA: https://boczkowska.github.io/test/
