### ISSUE TITLE
Optional: Update README, play around with :toc: 

### ISSUE THREAD

**Issue by boczkowska** [boczkowska/test#23]
Update README to include the address of out humble website https://boczkowska.github.io/test/

Play around with :toc: if you feel like it:
https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#table-of-contents-toc

It allows generation of table of contents. Reference: 
https://github.com/boczkowska/odo-docs
https://raw.githubusercontent.com/boczkowska/odo-docs/master/docs/assembly_developing-and-deploying-an-application-on-openshift-using-odo.adoc

**Comment by ossontoes** [comment]
Resolved in https://github.com/boczkowska/test/pull/30.
