### ISSUE TITLE
Add Github and GitLab links somewhere in the docs

### ISSUE THREAD

**Issue by boczkowska** [boczkowska/test#28]
So we have attributes for the links now, let's use them somewhere in the text and see how they are rendered. 
Example:
link:{gl-link}[GitLab homepage]

**Comment by ossontoes** [comment]
Added the links in https://github.com/boczkowska/test/pull/27.

https://github.com/ossontoes/test/blame/aaff06403ef5d8f50d2f0f460c65889d579bb198/docs/con_github-gitlab.adoc#L5
https://github.com/ossontoes/test/blame/aaff06403ef5d8f50d2f0f460c65889d579bb198/docs/con_github-gitlab.adoc#L14
