### ISSUE TITLE
Create a core structure for a git-themed cheatsheat

### ISSUE THREAD

**Issue by boczkowska** [boczkowska/test#3]
IMPORTANT: Make sure you work in your fork in a non-master branch.

You will need:

- [ ] master.adoc file - it will be your main assembly
- [ ] concept file - it will explain what `git` is, its key concepts and where it can be used; target audience - junior technical writers with little to no technical background
- [ ] procedure file - how to install `git`
- [ ] reference file - useful resources on `git`

Make sure your modules are properly named, include ids and generally adhere to modular content structure requirements and recommendations. Use templates to create new modules.

Feel free to either edit and rename existing modules in the directory or remove them and create new modules from scratch.

**Comment by boczkowska** [comment]
@ossontoes If you have any questions about the assignment ask them here.

**Comment by ossontoes** [comment]
Resolved in https://github.com/boczkowska/test/pull/13
